'use strict';
/**
 * 自动化功能自测：
 *  - 启动真实服务（PORT=3999），用 admin 登录
 *  - 验证：管理员入口链接、设置读写、立即运行一次（抓取→生成→发布）、去重、运行日志
 *  - 结束后清理自动生成的演示文章，保持站点整洁
 */
process.env.PORT = process.env.PORT || '3999';
const path = require('path');

let pass = 0, fail = 0;
function check(name, cond) {
  if (cond) { pass++; console.log('  ✅ ' + name); }
  else { fail++; console.log('  ❌ ' + name); }
}

function cookieFrom(res) {
  const sc = res.headers.get('set-cookie');
  if (!sc) return '';
  const arr = Array.isArray(sc) ? sc : [sc];
  return arr.map(c => c.split(';')[0]).join('; ');
}

(async () => {
  console.log('启动服务…');
  require('../server');
  await new Promise(r => setTimeout(r, 1200));

  const BASE = 'http://127.0.0.1:3999';
  let cookie = '';

  // 1) 登录管理员
  let r = await fetch(BASE + '/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ account: 'admin', password: 'Admin@888' }) });
  let j = await r.json();
  check('管理员登录成功', r.status === 200 && j.ok === true);
  cookie = cookieFrom(r);
  check('获取到会话 Cookie', !!cookie);

  // 2) 首页含"管理后台"入口（仅管理员可见）
  r = await fetch(BASE + '/', { headers: { Cookie: cookie } });
  let html = await r.text();
  check('首页渲染含管理后台入口', html.includes('管理后台') && html.includes('nav-admin'));

  // 3) 未登录不应看到管理后台入口
  r = await fetch(BASE + '/');
  html = await r.text();
  check('未登录不显示管理后台入口', !html.includes('nav-admin'));

  // 4) 读取设置
  r = await fetch(BASE + '/api/admin/settings', { headers: { Cookie: cookie } });
  j = await r.json();
  check('设置接口返回 ok', r.status === 200 && j.ok === true);
  check('设置含 llm 提供商', j.settings && Array.isArray(j.settings.llm.providers) && j.settings.llm.providers.length >= 1);
  check('设置含 rss 源', j.settings && Array.isArray(j.settings.rss.feeds) && j.settings.rss.feeds.length >= 1);
  check('设置含 automation 调度', j.settings && j.settings.automation && typeof j.settings.automation.startHour === 'number');
  check('API Key 已脱敏', j.settings.llm.providers.every(p => p.apiKey !== 'sk-real'));

  // 5) 修改提示词并保存
  const marker = '【自测标记提示词 ' + Date.now() + '】';
  const patch = {
    automation: { enabled: true, startHour: 4, endHour: 20, minute: 0, maxPerRun: 5, defaultPremium: false, defaultCategory: '' },
    rss: { mode: 'mock', feeds: j.settings.rss.feeds },
    llm: { activeProviderId: j.settings.llm.activeProviderId, providers: j.settings.llm.providers.map(p => ({ id: p.id, name: p.name, type: p.type, baseUrl: p.baseUrl, apiKey: p.apiKey, model: p.model, enabled: p.enabled })) }
  };
  patch.automation && (patch.automation.prompt = marker);
  r = await fetch(BASE + '/api/admin/settings', { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: cookie }, body: JSON.stringify(patch) });
  j = await r.json();
  check('保存设置成功', r.status === 200 && j.ok === true);
  check('提示词已更新', j.settings.automation.prompt === marker);

  // 6) 立即运行一次（mock 模式：抓取→生成→发布）
  r = await fetch(BASE + '/api/admin/run-once', { method: 'POST', headers: { Cookie: cookie } });
  j = await r.json();
  check('立即运行一次 ok', r.status === 200 && j.ok === true);
  check('本次抓取>=1', j.fetched >= 1);
  check('本次发布>=1', j.published >= 1);

  // 7) 首页能看到自动生成的文章（验证已真实发布）
  r = await fetch(BASE + '/', { headers: { Cookie: cookie } });
  html = await r.text();
  check('首页出现自动生成的时事（某主要经济体宣布新一轮基建投资计划）', html.includes('某主要经济体宣布新一轮基建投资计划'));

  // 8) 再次运行：去重，应跳过已发布（published=0, skipped>=1）
  r = await fetch(BASE + '/api/admin/run-once', { method: 'POST', headers: { Cookie: cookie } });
  j = await r.json();
  check('二次运行已去重（不重复发布）', j.published === 0 && j.skipped >= 1);

  // 9) 运行日志可读
  r = await fetch(BASE + '/api/admin/automation-log', { headers: { Cookie: cookie } });
  j = await r.json();
  check('运行日志非空', j.ok === true && Array.isArray(j.log) && j.log.length >= 1);

  // 10) 非管理员访问设置被拒
  r = await fetch(BASE + '/api/admin/settings');
  check('未登录访问设置被拒(403)', r.status === 403);

  // 清理：移除自动生成的演示文章，保持站点整洁
  try {
    const fs = require('fs');
    const f = path.join(__dirname, '..', 'data', 'articles.json');
    const list = JSON.parse(fs.readFileSync(f, 'utf8'));
    const cleaned = list.filter(a => !a.autoGenerated);
    fs.writeFileSync(f, JSON.stringify(cleaned, null, 2), 'utf8');
    console.log('  🧹 已清理自动生成的演示文章（共移除 ' + (list.length - cleaned.length) + ' 篇）');
  } catch (e) { console.log('  ⚠️ 清理演示文章失败：' + e.message); }

  console.log('\n结果：' + pass + ' 通过 / ' + fail + ' 失败');
  process.exit(fail === 0 ? 0 : 1);
})().catch(e => { console.error('自测异常', e); process.exit(1); });
