'use strict';
/**
 * 自动化调度与编排：
 *  - 每天 startHour–endHour 的每个整点（node-cron）自动运行
 *  - 流程：拉取时事(RSS/mock) → 逐条用自定义提示词调 AI 生成原创洞察 → 去重 → 自动发布
 *  - 支持注入 fetchFn/parseFn/callLlm 便于测试；支持"立即运行一次"（绕过时间窗）
 */
const cron = require('node-cron');
const fs = require('fs');
const settings = require('./settings');
const rss = require('./rss');
const llm = require('./llm');
const store = require('./store');
const { FILES } = require('./paths');

const LOG = FILES.automationLog;
let task = null;

function todayStr() {
  const d = new Date();
  const p = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function logRun(line) {
  const ts = new Date().toISOString();
  try { fs.appendFileSync(LOG, `[${ts}] ${line}\n`); } catch (e) { /* ignore */ }
}

function getRecentLog(n = 60) {
  try {
    const lines = fs.readFileSync(LOG, 'utf8').split('\n').filter(Boolean);
    return lines.slice(-n);
  } catch (e) { return []; }
}

function inWindow(s) {
  const h = new Date().getHours();
  return h >= s.automation.startHour && h <= s.automation.endHour;
}

function cronExpr(s) {
  return `${s.automation.minute} ${s.automation.startHour}-${s.automation.endHour} * * *`;
}

async function runPipeline(opts) {
  opts = opts || {};
  const s = opts.settings || settings.getSettings();
  const getProvider = opts.getProvider || (() => settings.getActiveProvider());
  const doFetchNews = opts.fetchNews || rss.fetchNews;
  const doFetchNewsMock = opts.fetchNewsMock || (() => Promise.resolve(rss.MOCK_ITEMS.map(x => Object.assign({}, x))));
  const callLlm = opts.callLlm || llm.generateInsight;

  logRun('开始运行自动化：rss.mode=' + s.rss.mode + ', maxPerRun=' + s.automation.maxPerRun);
  let items = s.rss.mode === 'mock'
    ? await doFetchNewsMock()
    : await doFetchNews(s.rss.feeds, { fetchFn: opts.fetchFn, parseFn: opts.parseFn });
  items = (items || []).slice(0, s.automation.maxPerRun);

  const existing = store.getArticles();
  let published = 0, skipped = 0;
  const provider = getProvider();

  for (const item of items) {
    if (item.link && existing.some(a => a.sourceUrl && a.sourceUrl === item.link)) {
      skipped++; logRun('跳过(已存在): ' + item.title); continue;
    }
    try {
      const insight = await callLlm({ provider, systemPrompt: s.automation.prompt, newsItem: item });
      const art = store.addArticle({
        id: 'auto' + Date.now() + Math.random().toString(36).slice(2, 6),
        slug: 'auto-' + Date.now() + '-' + Math.random().toString(36).slice(2, 5),
        category: item.category || s.automation.defaultCategory || '时政',
        author: '涟漪观察 · AI 洞察', date: todayStr(),
        title: insight.title || item.title, lead: insight.lead || '',
        isPremium: !!s.automation.defaultPremium, views: 0,
        freeHtml: insight.freeHtml || '', premiumHtml: insight.premiumHtml || '',
        impacts: (Array.isArray(insight.impacts) && insight.impacts.length) ? insight.impacts : [{ t: 'amber', l: '影响' }],
        sourceUrl: item.link || '', autoGenerated: true, aiProvider: provider ? provider.id : null
      });
      published++;
      logRun('已发布: ' + art.title);
    } catch (e) {
      logRun('生成失败: ' + item.title + ' -> ' + e.message);
    }
  }
  logRun(`本次完成：抓取 ${items.length} / 发布 ${published} / 跳过 ${skipped}`);
  return { fetched: items.length, published, skipped };
}

function startScheduler() {
  const s = settings.getSettings();
  const expr = cronExpr(s);
  if (task) { try { task.stop(); } catch (e) {} task = null; }
  task = cron.schedule(expr, async () => {
    const st = settings.getSettings();
    if (!st.automation.enabled) { logRun('自动化已关闭，跳过本次触发'); return; }
    if (!inWindow(st)) return;
    try { await runPipeline(); } catch (e) { logRun('运行异常: ' + e.message); }
  }, { timezone: 'Asia/Shanghai' });
  logRun('调度器已启动：' + expr + ' (enabled=' + s.automation.enabled + ')');
  return task;
}

module.exports = { runPipeline, startScheduler, inWindow, getRecentLog, logRun, cronExpr };
